# WARNING: overload tokens with env vars or a separate config file to avoid leaking secrets
env: demo
topic: univers-ecospheres
tag: ecospheres
datagouv:
  url: https://demo.data.gouv.fr
  token: CONFIGURE_ME
grist:
  url: https://grist.numerique.gouv.fr/o/ecospheres/api/docs/rvqUfg8tKC6uYfUy2Mt6a7
  table: Demo
  token: CONFIGURE_ME
