# overload with your own config file
env: demo
topic: univers-ecospheres
tag: ecospheres
grist_url: "https://grist.numerique.gouv.fr/o/ecospheres/api/docs/k3YQHL3Bmrhmpk8frjznZL/tables/Universe/records"
api:
  url: https://demo.data.gouv.fr
  token: CONFIGURE_ME
